import type { RosterPlayer } from "@/app/_lib/admin-roster-access";

// Pure filter + sort logic for the /admin/players roster
// (docs/admin-ui-spec.md §6.1), split out of RosterTable.tsx so it can be
// unit-tested without rendering a client component. Deliberately outside
// src/lib/** (same rationale as src/components/nav/tabs.ts): plain predicate
// logic, no consequence-critical numeric golden value.

export type RosterFilter =
  "all" | "humans" | "bots" | "not-tipped" | "attention";

export type RosterSort = "name" | "newest";

/**
 * Has an unfiled pick for the current gameweek AND is a person who would be
 * reminded. Bots are excluded -- their picks are generated by the sync job,
 * never by a nudge (CLAUDE.md -> bots). A null pick count means there is no
 * current gameweek at all, which is not "not tipped" (issue #200 decision 7).
 */
export function playerIsNotTipped(player: RosterPlayer): boolean {
  return !player.isBot && player.currentGameweekPickCount === 0;
}

/**
 * Needs attention = locked out, OR flagged for a PIN reset, OR a person who
 * hasn't tipped the current gameweek.
 */
export function playerNeedsAttention(player: RosterPlayer): boolean {
  return (
    player.lockedUntil !== null ||
    player.pinResetRequired ||
    playerIsNotTipped(player)
  );
}

export function matchesRosterFilter(
  player: RosterPlayer,
  filter: RosterFilter,
): boolean {
  switch (filter) {
    case "all":
      return true;
    case "humans":
      return !player.isBot;
    case "bots":
      return player.isBot;
    case "not-tipped":
      return playerIsNotTipped(player);
    case "attention":
      return playerNeedsAttention(player);
  }
}

/**
 * Default order: people before bots; within people, whoever needs the
 * admin's attention first; among those, the ones with no email on file
 * first (they can't be reminded automatically, so they're the manual
 * chases); then A-Z. The admin's scan-for-problems order.
 */
export function compareRosterDefault(a: RosterPlayer, b: RosterPlayer): number {
  if (a.isBot !== b.isBot) return a.isBot ? 1 : -1;

  const aAttention = playerNeedsAttention(a);
  const bAttention = playerNeedsAttention(b);
  if (aAttention !== bAttention) return aAttention ? -1 : 1;

  if (aAttention && bAttention && a.hasEmail !== b.hasEmail) {
    return a.hasEmail ? 1 : -1;
  }

  return a.displayName.localeCompare(b.displayName);
}

/** Newest signups first -- for spotting people who joined recently. */
export function compareRosterNewest(a: RosterPlayer, b: RosterPlayer): number {
  const byDate =
    new Date(b.joinedAt).getTime() - new Date(a.joinedAt).getTime();
  return byDate !== 0 ? byDate : a.displayName.localeCompare(b.displayName);
}

export function sortRoster(
  players: readonly RosterPlayer[],
  sort: RosterSort,
): RosterPlayer[] {
  return [...players].sort(
    sort === "newest" ? compareRosterNewest : compareRosterDefault,
  );
}
